### ISSUE TITLE
nnp_convolution_output throws exception in some cases.

### ISSUE THREAD

**Issue by tsyj0404** [zeno40/convnet#1]
Dear developer,@zeno40 

thank you for your contribution. This version can be used in windows. But the function "nnp_convolution_output" throws exception in some cases.
For example, the code is:

	enum nnp_convolution_algorithm algorithm = nnp_convolution_algorithm_auto;
	const size_t batch_size = 1;
	const size_t input_channels = 1;
	const size_t output_channels = 64;
	const struct nnp_padding input_padding = { 0, 0, 0, 0 };
	const struct nnp_size input_size = { 10, 10 };
	const struct nnp_size kernel_size = { 2, 2 };
	const struct nnp_size output_size = {9,9};
	float* input = (float*)malloc(batch_size * input_channels *input_size.height *input_size.width * 	sizeof(float));
	float* kernel = (float*)malloc(input_channels * output_channels * kernel_size.height * kernel_size.width * sizeof(float));
	float* output = (float*)malloc(batch_size* output_channels * output_size.height * output_size.width * sizeof(float));

	float* bias = (float*)malloc(output_channels * sizeof(float));

	int i, j;
	for (int c = 0; c<input_channels; c++) {
	for (i = 0; i<input_size.height; i++) {
		for (j = 0; j<input_size.width; j++) {
			input[c*input_size.height*input_size.width + i*input_size.width + j] = (i*input_size.width + j)*1.0;
		}
	}
	}

	//init kernel data  
	for (int i = 0; i<output_channels; i++) {
	for (j = 0; j<input_channels*kernel_size.height*kernel_size.width; j++) {
		kernel[i*input_channels*kernel_size.height*kernel_size.width + j] = 1.0;
	}
	}

	//init bias data  
	for (int i = 0; i<output_channels; i++) {
	bias[i] = 0.0;
	}
	nnp_workspace_pointers pointers_output;
	pointers_output.input = NULL;
	pointers_output.output = NULL;
	pointers_output.kernel = NULL;
	nnp_convolution_output(algorithm,
		batch_size,
		input_channels,
		output_channels,
		input_size,
		input_padding,
		kernel_size,
		input,
		kernel,
		bias,
		output,
		&pointers_output);

than I will get "unhandled exception, Access violation executing location ...."
It seems that when output_channels is small, such as 10, it works well, but if the value is big, 64, this function will be broken.

So what's the problem? Are there any bugs in my code?

Thank you !

**Comment by zeno40** [comment]
Hi,

I don't think 2x2 kernels are supported with nnpack.

**Comment by zeno40** [comment]
Just did a test and I was wrong! 2x2 kernels are supported but I don't know if a batch_size of one is the culprit? Can you do the test again with a batch_size greater than one.

thanks,
filip

**Comment by tsyj0404** [comment]
Thanks for your attention.
It’s not the problem about batch_size. The above program does work if the output_channels is small, like 10, and the batch_size of one is okay. 
It seems that the matrix cannot be big for a successful operation.

**Comment by tsyj0404** [comment]
I find the location of exception:  #646 in function compute_fast_convolution_inference in file convolution_inference.cpp (the function nnp_convolution_inference -> compute_fast_convolution_inference ) , there seems to be a problem with pthreadpool_compute_2d_tiled. In fact, I just use single thread, so what  should I do to fix this problem?

**Comment by zeno40** [comment]
I found the bug in file convolution_inference.cpp you have to switch line 635 with line 636.
like this:
struct tuple_multiplication_context tuple_multiplication_context = 
						{
							tuple_elements,
							tiles_subblock_max,
							input_channels_block_size,
							input_channels_block_start,
							output_channels,
							output_channels_subblock_max,
							output_channels_block_start,
							input_transform + tuple_index * tiles_count * input_channels_block_size * tuple_elements,
							kernel_transform + tuple_index * output_channels * input_channels_block_size * tuple_elements,
							output_transform + tuple_index * tiles_count * output_channels * tuple_elements,
							fast_gemm_function,
							full_gemm_function
						};

**Comment by tsyj0404** [comment]
Thank you! This problem has been solved.
